explainer.md, webidl.txt
Addresses #5 
PTAL @pthatcherg
=> Add detailed design discussion for codec configuration

explainer.md, webidl.txt
Some of the examples were too long or complex.  This makes them more simple.
We also fix a small naming mistake in the WebIDL file.
=> Shorten and simplify examples

index.src.html
This fixes a handful of formatting/style issues and attempts to rely more on concepts from the infra spec. 
Still to come, I'm working on PR to refactor the relationship of methods/algorithms for the codec interfaces. What I have currently reduces copy paste, but its a bit hard to read.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/109.html" title="Last updated on Dec 8, 2020, 6:01 PM UTC (b58f164)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/109/c15fbb0...b58f164.html" title="Last updated on Dec 8, 2020, 6:01 PM UTC (b58f164)">Diff</a>
=> Small cleanups and feedback from @mounirlamouri

index.src.html
Make Security Considerations example less verbose
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/135.html" title="Last updated on Feb 8, 2021, 3:07 PM UTC (813b10c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/135/06da4b3...813b10c.html" title="Last updated on Feb 8, 2021, 3:07 PM UTC (813b10c)">Diff</a>
=> Make Security Considerations example less verbose

index.src.html
Fixes #122
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/140.html" title="Last updated on Feb 11, 2021, 4:48 AM UTC (e303378)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/140/9baf37c...e303378.html" title="Last updated on Feb 11, 2021, 4:48 AM UTC (e303378)">Diff</a>
=> Use DOMHighResTimeStamp for all timestamps/durations

index.src.html
We haven't thought through the implications of exposing to SharedWorker
and ServiceWorker yet. Mentioned briefly in #121. Also #43.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/139.html" title="Last updated on Feb 11, 2021, 3:52 AM UTC (b59de85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/139/2d2f06b...b59de85.html" title="Last updated on Feb 11, 2021, 3:52 AM UTC (b59de85)">Diff</a>
=> Expose interfaces to DedicatedWorker, not Worker

index.src.html
This is required by Web IDL since VideoFrameInit has no required members.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/web-codecs/pull/142.html" title="Last updated on Feb 17, 2021, 1:26 PM UTC (c52a5c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/142/4905c4f...foolip:c52a5c7.html" title="Last updated on Feb 17, 2021, 1:26 PM UTC (c52a5c7)">Diff</a>
=> Make VideoFrameInit arguments optional

index.src.html
Reverts WICG/web-codecs#140
I pressed merged on this one by mistake sorry.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/141.html" title="Last updated on Feb 16, 2021, 5:14 PM UTC (97281d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/141/bbdd988...97281d7.html" title="Last updated on Feb 16, 2021, 5:14 PM UTC (97281d7)">Diff</a>
=> Revert "Use DOMHighResTimeStamp for all timestamps/durations"

index.src.html
Earlier drafts wrongly assumed that support could be determined
synchronously.This remedies that by introducing a new async API
to check support prior to calling configure().
Fixes #98. See additional discussion there.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/120.html" title="Last updated on Feb 17, 2021, 10:21 PM UTC (6fc501a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/120/aec3834...6fc501a.html" title="Last updated on Feb 17, 2021, 10:21 PM UTC (6fc501a)">Diff</a>
=> Define static async isConfigSupported()

.gitignore, Makefile, avc_codec_registration.src.html, codec_registry.src.html, index.src.html
This moves codec-specific defintions / descriptions into a registry.
I've also added some text to the main document to clarify that support
for any given codec is not required.
Fixes #143. Fixes #126.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/149.html" title="Last updated on Mar 17, 2021, 11:39 PM UTC (49baae7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/149/57e2560...49baae7.html" title="Last updated on Mar 17, 2021, 11:39 PM UTC (49baae7)">Diff</a>
=> Establish codec registry and AVC registration.

CONTRIBUTING.md, LICENSE.md, Makefile, README.md, avc_codec_registration.src.html, codec_registry.src.html, explainer.md, index.src.html, w3c.json
**To be merged only once repo transition has happened!**
This update adjusts the metadata of the spec as it gets adopted by the Media
Working Group, and makes the following changes:
- Update CONTRIBUTING.md to match that used in W3C
- Update LICENSE.md to drop the CLA part
- Update links in README.md and to mention Media WG
- Update w3c.json
- Update status, group, and links that currently target the WICG repo in the
spec itself
Also note the switch to `Level: None` in the metadata of the spec as I suspect
that the group will publish the API without any level, at least initially.
Linked to #130.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/150.html" title="Last updated on Mar 29, 2021, 8:33 AM UTC (a0aee72)">Preview</a> | <a …
=> Migrate spec to Media WG

index.src.html
Note: videoframe.destroy() is being renamed to close() in a follow up
change. I'll use close() to describe the change below.
This seems surprsiing in inconsistent with other APIs. Having the user
close() after calling encode is fine. Users will similarly need to close
frames coming out of the decoder or TrackProcessor.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/163.html" title="Last updated on Apr 2, 2021, 11:59 PM UTC (b34a6c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/163/4b76877...b34a6c1.html" title="Last updated on Apr 2, 2021, 11:59 PM UTC (b34a6c1)">Diff</a>
=> Make encode(frame) not auto-close its frames

avc_codec_registration.src.html, codec_registry.src.html, index.src.html
Changes:
- Add link to the TR document
- Add link to previous version
- Drop now useless local biblio, as specs now exist in Specref. Anchors sections are still needed for now though.
- google.com is a permanent redirect to www.google.com, use the latter form to avoid the redirect.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/171.html" title="Last updated on Apr 8, 2021, 10:19 AM UTC (8f7e182)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/171/bee232d...8f7e182.html" title="Last updated on Apr 8, 2021, 10:19 AM UTC (8f7e182)">Diff</a>
=> Adjust metadata following publication as FPWD

index.src.html
Fixes #151
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/172.html" title="Last updated on Apr 9, 2021, 6:54 AM UTC (cd61686)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/172/eefd4c2...cd61686.html" title="Last updated on Apr 9, 2021, 6:54 AM UTC (cd61686)">Diff</a>
=> Add bitrate to AudioEncoderConfig

index.src.html
For VideoDecoderConfig, the coded size attributes are no longer
required. They only serve as a hint for the UA to create an approriate
underlying decoder (e.g. hardware accelerated for higher resolutions)
and are not strictly required. Fixes #94.
For VideoEncoderConfig, cropWidth and cropHeight are renamed to simply
be width and height. The crop prefix was added in #113 as I realized
that we were describing the "crop" size of the encoded VideoFrames. But
I now think this risks giving the impression that the encoder is going
to crop frames. Being intuitive is more important than being pedantic.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/186.html" title="Last updated on Apr 21, 2021, 5:55 AM UTC (059860b)">Preview</a> | <a …
=> Minor changes to width/height config members.

index.src.html
Adds slots for all VideoFrame attributes and updates all references to attributes to instead reference the slots. This is an increment step toward resolving #184.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/190.html" title="Last updated on Apr 23, 2021, 10:03 PM UTC (6a09f88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/190/464f905...6a09f88.html" title="Last updated on Apr 23, 2021, 10:03 PM UTC (6a09f88)">Diff</a>
=> Define internal slots as backing for VideoFrame attributes

.github/workflows/pr-push.yml
The `secrets` context is not available at the `matrix` level. See discussion in:
https://github.com/w3c/spec-prod/issues/55#issuecomment-827576189
Workaround is to list the secret name at that level and to dereference it in the actual step.
=> [spec-prod] Dereference secret name in step

.github/workflows/pr-push.yml
One job runs for each of the 3 documents in the repository. Each of them updates the "gh-pages" branch. Problem is that these jobs are typically run in parallel, leading to "not up to date" issues when "git push" commands are run.
For an example of such a problem, see:
https://github.com/w3c/webcodecs/runs/2462176606
Also see discussion in:
https://github.com/w3c/spec-prod/issues/58
This update tells GitHub to serialize the jobs. Since the jobs are relatively independent otherwise, it also tells GitHub to run them to completion even when one of them fails.
=> [Auto publication] Force job serialization

avc_codec_registration.src.html, codec_registry.src.html, index.src.html
Spec-prod attempts to override the "Previous version" link in the documents before generation with Bikeshed, but this is not a real override, leading to specs with two Previous Version links, see:
https://github.com/tabatkins/bikeshed/issues/2041
In turn, this makes publication fail when spec gets published multiple times on the same day (because "from biblio" then reports the same URL as the "This Version" link).
Dropping the "Previous version" link from the ED fixes the issue. The link is not useful in an ED in any case.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/216.html" title="Last updated on May 4, 2021, 9:34 AM UTC (da659e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/216/209a2a0...da659e4.html" title="Last updated on May 4, …
=> Drop Previous Version link from ED

.github/workflows/deploy-samples.yml
The job runs on pushes to the main branch that touch the "samples" folder and the deploy script itself. It deploys the contents of that folder to the "samples" folder in the "gh-pages" branch.
The job may also be run manually from the GitHub admin UI.
=> Add job to deploy samples to gh-pages branch

samples/README.md, samples/index.html, samples/mp4-decode/index.html
WebCodecs is hosted at https://w3c.github.io/webcodecs/, which means that hrefs starting with '/samples/' need to start with '/webcodecs/samples/' instead.
This PR also adds a convenience link to the samples from the github /samples/readme.md.
=> Update sample links and add readme.md

samples/index.html, samples/webcam-in-worker/index.html, samples/webcam-in-worker/stream_worker.js
This commit migrates a demo showcasing how to transfer MediaStreamTrackProcessor's ReadableStream to a  worker. The original demo's link is:
https://tguilbert-google.github.io/webcodecs/mstp_worker/index.html
=> Migrate 'webcam in worker' demo

samples/image-decoder/animated-gif-renderer.html, samples/mp4-decode/index.html
The current OT tokens are valid for tguilbert-google.github.io, and not w3c.github.io.
=> Update OT tokens

index.src.html
Optional dictionary arg must have a default value of `{}`, see related text in
WebIDL in:
https://heycam.github.io/webidl/#dfn-optional-argument-default-value
"If the type of an argument is a dictionary type or a union type that has a
dictionary type as one of its flattened member types, and that dictionary type
and its ancestors have no required members, and the argument is either the final
argument or is followed only by optional arguments, then the argument must be
specified as optional and have a default value provided."
Also, interface definitions must have an "Exposed" extended attribute.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/229.html" title="Last updated on May 6, 2021, 7:07 AM UTC (d2ab661)">Preview</a> | <a …
=> Fix WebIDL

samples/index.html
The card is missing  `.../samples/...` in its href, which the title correctly has.
=> Fix "Capture to File" sample card href

index.src.html
Fixes #122
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/248.html" title="Last updated on May 17, 2021, 3:43 AM UTC (bfc9465)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/248/ec00a4f...bfc9465.html" title="Last updated on May 17, 2021, 3:43 AM UTC (bfc9465)">Diff</a>
=> Make timestamps/durations int64 microseconds

codec_registry.src.html
The link to the AVC spec is fine in the ED of the registry spec, but breaks when the spec is published to /TR because the AVC spec gets published to a different folder.
This update switches link to use an absolute URL.
=> Fix semi-broken link to AVC WebCodecs Registration

index.src.html
Following up on this TODO
https://github.com/w3c/webcodecs/pull/162/files#r625845109
Fixes #179 
Fixes #223
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/228.html" title="Last updated on May 26, 2021, 9:40 PM UTC (c2a1c9c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/228/47196de...c2a1c9c.html" title="Last updated on May 26, 2021, 9:40 PM UTC (c2a1c9c)">Diff</a>
=> Define AudioDataCopyToOptions with frameOffset and frameCount

index.src.html
VideoDecoderConfig's cropHeight, cropWidth, cropTop and cropLeft are all deprecated, and need to be removed.
Remaining references to crop* on VideoFrame and VideoFramePlaneInit will be removed in upcoming PRs dealing with VisibleRegions.
This should address issue #94.
***
<a href="https://pr-preview.s3.amazonaws.com/tguilbert-google/webcodecs/pull/250.html" title="Last updated on May 26, 2021, 10:12 PM UTC (48e8fdb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/250/0db2aae...tguilbert-google:48e8fdb.html" title="Last updated on May 26, 2021, 10:12 PM UTC (48e8fdb)">Diff</a>
=> Remove crop* from VideoDecoderConfig

index.src.html
Fixes #220. That issue focuses on flush(), but configure() suffers the same issue and should have the same solution.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/247.html" title="Last updated on May 26, 2021, 10:58 PM UTC (282aa69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/247/0cfee37...282aa69.html" title="Last updated on May 26, 2021, 10:58 PM UTC (282aa69)">Diff</a>
=> Require 'key' chunks after flush() and configure()

index.src.html
Noteworthy things:
- Added `U8P`
- Added `S24` variant. Otherwise, there is no way to distinguish between 24bit audio sample and 32bit audio samples (this exists, in WAV). This follows what ffmpeg and others do.
Otherwise, probably what you'd have expected.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/256.html" title="Last updated on May 27, 2021, 9:04 AM UTC (3a8b026)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/256/97e81bd...3a8b026.html" title="Last updated on May 27, 2021, 9:04 AM UTC (3a8b026)">Diff</a>
=> Add description of audio sample types

index.src.html
Matching VideoFrame is good. Sample format is more to type and the meaning of 'format' seems pretty intuitive given the context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/264.html" title="Last updated on Jun 2, 2021, 4:58 AM UTC (d14b5a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/264/7730b88...d14b5a4.html" title="Last updated on Jun 2, 2021, 4:58 AM UTC (d14b5a4)">Diff</a>
=> Rename AudioData.sampleFormat -> AudioData.format to match VideoFrame

index.src.html
Matches what was done for AudioData. No reason not to allow the broader BufferSource union, including SharedArrayBuffer.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/263.html" title="Last updated on Jun 2, 2021, 4:52 AM UTC (3b6a72b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/263/7730b88...3b6a72b.html" title="Last updated on Jun 2, 2021, 4:52 AM UTC (3b6a72b)">Diff</a>
=> Make Encoded*Chunk.copyTo(...) accept [AllowShared]BufferSource

index.src.html
Earlier PR to make timestamp signed long long got a little carried away and changed duration as well. The two should both be long long microseconds, but only timestamp should be signed (negative duration isn't a thing).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/262.html" title="Last updated on Jun 2, 2021, 4:43 AM UTC (2f32ac4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/262/7730b88...2f32ac4.html" title="Last updated on Jun 2, 2021, 4:43 AM UTC (2f32ac4)">Diff</a>
=> Leave duration unsigned long long.

index.src.html
This PR fixes a number of typos I spotted while reading through the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/272.html" title="Last updated on Jun 8, 2021, 9:50 AM UTC (c000cd4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/272/16b948c...c000cd4.html" title="Last updated on Jun 8, 2021, 9:50 AM UTC (c000cd4)">Diff</a>
=> Fixed some typos

index.src.html
This PR moves the `temporalLayerId` into a dedicated `svc` dictionary, freeing up the top level `EncodedVideoChunkMetadata` object.
***
<a href="https://pr-preview.s3.amazonaws.com/tguilbert-google/webcodecs/pull/283.html" title="Last updated on Jun 17, 2021, 6:30 PM UTC (d72fc4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/283/a96a6d7...tguilbert-google:d72fc4f.html" title="Last updated on Jun 17, 2021, 6:30 PM UTC (d72fc4f)">Diff</a>
=> Move SVC data to its own dictionnary

index.src.html
Transfer "moves", serialize "clones".
Fixes #210.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/286.html" title="Last updated on Jul 14, 2021, 3:12 AM UTC (8d259de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/286/f73dd2c...8d259de.html" title="Last updated on Jul 14, 2021, 3:12 AM UTC (8d259de)">Diff</a>
=> Make VideoFrame/AudioData Transferable and Serializable

index.src.html
Please have a look. Which other formats do we need to support initially (= what formats does Chrome plan to ship with) ? I know there was mentions of NV12.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/288.html" title="Last updated on Jul 15, 2021, 2:07 PM UTC (81759cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/288/3584fb9...81759cc.html" title="Last updated on Jul 15, 2021, 2:07 PM UTC (81759cc)">Diff</a>
=> Define some pixel formats

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/312.html" title="Last updated on Jul 28, 2021, 3:43 PM UTC (9c89379)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/312/88e74a4...9c89379.html" title="Last updated on Jul 28, 2021, 3:43 PM UTC (9c89379)">Diff</a>
=> Fix copy/paste error in the AudioDecoder.decode definition

index.src.html
Fixes #294
- Removes references to "frame's" in `AudioData` methods.
- Throws `InvalidStateError` when `allocationSize()` or `copyTo()` are called on detached objects.
***
<a href="https://pr-preview.s3.amazonaws.com/sandersdan/webcodecs/pull/310.html" title="Last updated on Jul 27, 2021, 7:34 PM UTC (2ef4fac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/310/88e74a4...sandersdan:2ef4fac.html" title="Last updated on Jul 27, 2021, 7:34 PM UTC (2ef4fac)">Diff</a>
=> Throw InvalidStateError for detached calls.

.github/workflows/auto-publish.yml, .gitignore, Makefile, avc_codec_registration.src.html, codec_registry.src.html, vorbis_codec_registration.src.html
Does what it says. I have an open question:
Are the three header packet required, or just the last one? The first one allows getting the channel number/sample-rate, what if it contradicts what has been passed in? Do we consider it kind of part of the container and expect authors to bit-shift their way to this piece of info to set up the decoder (which would work, but then it's clearly in the codec bytestream, so that's unclear), or do we state (like is in the proposed text here) that the values in the `AudioDecoderConfig` are not required, or ignored ? The second header is useless for Web Codecs in any case.
=> Add Vorbis to the registry

index.src.html
I've left off a note about fussiness around parameters, since that's
going to be codec implementation dependent.
Fixes: #253
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/321.html" title="Last updated on Aug 4, 2021, 12:31 AM UTC (9dab195)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/321/03e42e7...9dab195.html" title="Last updated on Aug 4, 2021, 12:31 AM UTC (9dab195)">Diff</a>
=> Clarify codec string requirements around profile, level, constraint.

index.src.html
Fixes: #55
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/320.html" title="Last updated on Aug 3, 2021, 10:47 PM UTC (d0b5043)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/320/03e42e7...d0b5043.html" title="Last updated on Aug 3, 2021, 10:47 PM UTC (d0b5043)">Diff</a>
=> Add presentation order text to standard

index.src.html
Per the resolution of the chairs, WebCodecs will be exposed in
windows and worker contexts. As part of that resolution the
chairs asked that we include a best practices section.
This section recommends authors move their media pipelines to
worker contexts where possible and highlights areas of concern
for those who still choose to operate in a worker.
Fixes: #211
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/316.html" title="Last updated on Jul 30, 2021, 12:41 AM UTC (44740f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/316/03e42e7...44740f6.html" title="Last updated on Jul 30, 2021, 12:41 AM UTC (44740f6)">Diff</a>
=> Add best practices section for using WebCodecs.

Makefile
This uses the same targets (no target for local development and remote for the CI), but won't
need any further modification to change the list of files to process.
Additionally, it checks an environment variable called
WEBCODECS_IGNORE_WARNINGS, so that folks that add new registry entries
can still have their new document generated.
=> Generalize the Makefile

.github/workflows/auto-publish.yml, .gitignore, codec_registry.src.html, flac_codec_registration.src.html
This is how ffmpeg and Gecko work for `.flac` files (although it also seems to support a mode where all blocks are passed to the decode method?), and the [Matroska embedding](https://www.matroska.org/technical/codec_specs.html#a_flac) works this way as well. FLAC in OGG work with minimal demuxing (essentially skipping a fixed number of bytes it seems). Audio packets are the same.
Please don't look at the Makefile changes, it's just so that it builds.
=> Add FLAC to the registry

.github/workflows/auto-publish.yml, .gitignore, codec_registry.src.html, opus_codec_registration.src.html
This has the `Makefile` changes so it builds, but I'll rebase that.
In contrast to Vorbis, the rate and channel count are required ahead of time here. The rate must be in [8, 12, 16, 24, 48] kHz, and the channel count is either 1 or 2, this is a user request, the decoder outputs what is requested as long as it's a valid Opus bytestream.
=> Add Opus to the registry

.github/workflows/auto-publish.yml, .gitignore, codec_registry.src.html, vp9_codec_registration.src.html
Add VP9 to the codec registry.
As titled. This adds VP9 to the registry following the model used by recent
audio codec registry additions like FLAC.
=> Add VP9 to the codec registry.

.github/workflows/auto-publish.yml
There were some issues with the merges for the vp8, vp9 additions. Fix the duplication.
=> Fix accidental duplication in workflow for codec registry.

index.src.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 10, 2021, 7:12 PM UTC)_.
<details>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebcodecs%2F71b7d1aef7afe8eae6e41868f599bc72f144a353%2Findex.src.html&md-warning=not%20ready)
```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 6, in 
cli.main()
File …
```
=> Fix post-commit review comments for window/worker text.

index.src.html
Fixes #47
:)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/306.html" title="Last updated on Aug 11, 2021, 5:54 AM UTC (41253c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/306/b43d3df...41253c5.html" title="Last updated on Aug 11, 2021, 5:54 AM UTC (41253c5)">Diff</a>
=> Define video color space interfaces and members

index.src.html
This PR unifies the units and uses of `duration` duration for `EncodedAudioChunk` and `EncodedAudioChunkInit`.
This aligns the Audio and Video definitions of duration.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 10, 2021, 4:42 AM UTC)_.
<details>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebcodecs%2F03e42e70a03f514c045787fce4a20f74a8c4a0d5%2Findex.src.html&md-warning=not%20ready)
```
Error running …
```
=> Update Audio duration references

index.src.html
The constructor takes a `VideoColorSpaceInit` dictionary as input that does not have any required parameter. Quoting from the Web IDL spec, the input "must be specified as optional and have a default value provided. This is to encourage API designs that do not require authors to pass an empty dictionary value when they wish only to use the dictionary’s default values."
https://heycam.github.io/webidl/#idl-operations
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webcodecs/pull/337.html" title="Last updated on Aug 12, 2021, 7:33 AM UTC (81ddaac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/337/2ef514e...tidoust:81ddaac.html" title="Last updated on Aug 12, 2021, 7:33 AM UTC (81ddaac)">Diff</a>
=> Make VideoColorSpace constructor argument optional

Makefile, index.src.html
* It's now a hint instead of being required.
* Values are noPreference, preferSoftware, and preferHardware.
Fixes: #239
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/313.html" title="Last updated on Aug 16, 2021, 11:55 PM UTC (4ea4dc6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/313/79a1416...4ea4dc6.html" title="Last updated on Aug 16, 2021, 11:55 PM UTC (4ea4dc6)">Diff</a>
=> Revise hardwareAcceleration based on consensus decision.

index.src.html
Makes colorSpace attributes non-nullables and removes
VideoEncoderConfig.colorSpace. See issues.
Fixes #341 and #345.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/346.html" title="Last updated on Aug 18, 2021, 6:23 PM UTC (5476d1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/346/fe0cb9c...5476d1a.html" title="Last updated on Aug 18, 2021, 6:23 PM UTC (5476d1a)">Diff</a>
=> Updates to VideoColorSpace attributes

.github/workflows/auto-publish.yml, .gitignore, aac_codec_registration.src.html, codec_registry.src.html
This is for now only speccing that the is ADTS frames like in MSE. There's probably some value in accepting raw AAC packets`raw_aac()` + the (at least) two bytes of extradata (`DecoderSpecificInfo`) so that authors don't have to remux.
=> Add AAC to the registry

index.src.html
This is split in multiple commits for ease of review, but the second commit has most of the actual changes.
There is a single occurrence that I thought was good to make normative (third commit). It's a MAY, so it's not a requirement per se.
Also, three section (background, and recommendation for developers) are non-normative, marked as such, and their prose has been fixed.
I'm not sure yet if we want to capitalize the words, maybe we do. This is easily done in any case, because they only appear normatively now.
This fixes #301.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/340.html" title="Last updated on Aug 20, 2021, 1:34 PM UTC (3d41cca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/340/55d1848...3d41cca.html" title="Last updated on Aug …
=> Replace uses of rfc2119 keywords in non-normative sections

index.src.html
Allows metadata override for efficient crop/resize.
Fixes #281.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/347.html" title="Last updated on Sep 7, 2021, 11:44 PM UTC (526d28f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/347/55d1848...526d28f.html" title="Last updated on Sep 7, 2021, 11:44 PM UTC (526d28f)">Diff</a>
=> Add visibleRect and displayWidth|Height to VideoFrameInit

index.src.html
Fixes #232.
Also, I've added validation of copyTo options to both allocationSize() and
copyTo() (previously only the latter), such that any call to
allocationSize() that succeeds should also succeed with copyTo().
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/349.html" title="Last updated on Sep 7, 2021, 11:50 PM UTC (771b5d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/349/f25d932...771b5d5.html" title="Last updated on Sep 7, 2021, 11:50 PM UTC (771b5d5)">Diff</a>
=> Add format to AudioDataCopyToOptions to convert

mp3_codec_registration.src.html
This PR fixes a minor formatting issue in the codec string list in the MP3 registry entry.
=> Fix MP3 codec string list formatting

codec_registry.src.html
I noticed that the WebCodecs registry linked to the Vorbis spec rather than the registry entry.
=> Fix link to Vorbis WebCodecs Registration

index.src.html
Authors who set bitrate should consider also setting framerate. We can generally detect framerate from timestamps, but providing a hint up front avoids assumptions for early frames.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/356.html" title="Last updated on Sep 16, 2021, 12:06 AM UTC (4989ca5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/356/9f27069...4989ca5.html" title="Last updated on Sep 16, 2021, 12:06 AM UTC (4989ca5)">Diff</a>
=> Add note encouraging VideoEncoderConfig.framerate

index.src.html
MSE-for-WebCodecs feature specification [1] needs to normatively
reference these concepts.
[1] https://github.com/w3c/media-source/issues/184
***
<a href="https://pr-preview.s3.amazonaws.com/wolenetz/webcodecs/pull/372.html" title="Last updated on Sep 30, 2021, 11:49 PM UTC (c33f68b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/372/206b991...wolenetz:c33f68b.html" title="Last updated on Sep 30, 2021, 11:49 PM UTC (c33f68b)">Diff</a>
=> Export dfns for valid audio and video decoder cfgs

explainer.md
Adds links to working samples.
Also removes a section on SVC configuration that isn't yet in the spec. We will probably add such options but I worry this was confusing folks by mixing roadmap w/ existing features.
=> Update explainer examples

.gitignore, alaw_codec_registration.src.html, codec_registry.src.html, pcm_codec_registration.src.html, ulaw_codec_registration.src.html
Our earlier thinking was that alaw and ulaw did not needing registration documents, as they have simple codec strings and no need for AudioDecoderConfig.description bytes. But we've since used the registry to define the details of EncodedAudioChunk's internal data, so registration documents are added to provide those details. 
With this, the The TODOs are now all addressed, so  inline ISSUEs can be removed.
=> Register alaw, ulaw, and linear pcm. Remove stale inline issues.

aac_codec_registration.src.html, av1_codec_registration.src.html, avc_codec_registration.src.html, codec_registry.src.html, flac_codec_registration.src.html, opus_codec_registration.src.html, vorbis_codec_registration.src.html, vp8_codec_registration.src.html, vp9_codec_registration.src.html
Details of registrations are unchanged. This just moves the sections around to arrive at a uniform ordering. It also includes an update to  the registry requirements to describe that ordering.
=> Cleanup registration requirements/ordering.

samples/mp4-decode/demux_decode_worker.js, samples/mp4-decode/index.html, samples/mp4-decode/mp4_demuxer.js
This PR moves the MP4 demux+decode demo to fetch, demux and decode in a worker, posting frames back to the main thread.
This change is done in order to align our demos with the recommended best practice of offloading webcodecs from the main window to workers.
=> Move MP4 demuxe/decode demo to workers

index.src.html
The spec confused the `hidden` attribute with the `visibilityState` attribute. The latter is a string that can take the value `"hidden"`. The [former is a boolean](https://html.spec.whatwg.org/multipage/interaction.html#dom-document-hidden) that is true when `visibilityState` equals `"hidden"`.
This update fixes that and drops the now useless reference to the Page Visibility spec (now integrated in HTML).
(triggered by @kainino0x's comment in https://github.com/w3c/webcodecs/pull/412#issuecomment-989469534)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webcodecs/pull/419.html" title="Last updated on Dec 9, 2021, 11:07 AM UTC (61fc705)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/419/8c5301a...tidoust:61fc705.html" title="Last updated on Dec 9, 2021, …
=> Compare Document.hidden with a boolean

codec_registry.src.html
This PR fixes the Linear PCM entry, which currently links to the A-Law entry in the References section.
=> Fix reference to PCM codec registration

index.src.html
Fixes #435.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/438.html" title="Last updated on Feb 9, 2022, 9:00 PM UTC (d75d11c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/438/14cf28f...d75d11c.html" title="Last updated on Feb 9, 2022, 9:00 PM UTC (d75d11c)">Diff</a>
=> Add MIME "type" attribute to ImageDecoder

index.src.html
Implementation of my proposal in #348.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/402.html" title="Last updated on Feb 16, 2022, 9:02 PM UTC (f29b0fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/402/c5ecb85...f29b0fb.html" title="Last updated on Feb 16, 2022, 9:02 PM UTC (f29b0fb)">Diff</a>
=> Support odd-sized visibleRects

codec_registry.src.html
This is to match expected practice in the WG, and the process we're following for reviewing the proposed H.263 registration.
=> Describe that WG consensus is needed to add registry entries

index.src.html
A few changes
* Updates process model to process control message queue entirely on the main thread. This aligns spec with Chrome, fixing #494.
* Moving ^that processing to the main thread means we need to be more explicit about when the loop is blocked/exited. For example, an implementation may block processing a decode() call when it finds the decoder is saturated by active decodes. Previously we elided description of this blocking behavior because the blocked loop lived on another thread, which was unobservable (beyond the queue size attributes). But with message processing happening entirely on the main (control) thread, we're motivated to be more explicit (we can't block scripts). 
* Named "codec" and "control" threads are removed to be more idiomatic with other W3C specs. WebAudio …
=> Revise processing model, fix queue size attributes

index.src.html
We decided not to do this, but forgot to remove it from the spec. The fact that
decode() calls stall until the next frame is available and the availability of the
`completed` promise make it largely unnecessary.
Clients which don't want to wait for for `completed` can instead handle a
RangeError exception during decode() if no more frames remain. While not
ideal it's inefficient to implement something like onchange since common
formats like GIF would require us to attempt decode in order to update the
frame count.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 6, 2022, 11:07 PM UTC)_.
<details>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one: …
=> Remove ImageTrack.onchange event.

samples/mp4-decode/mp4_demuxer.js
Reverts w3c/webcodecs#489
The original commit broke the sample
'Error handling response: TypeError: Cannot read properties of undefined (reading 'filter')'
=> Revert "Fix the problem that getAvccBox cannot get the value when the first track of the video is not AVC"

samples/mp4-decode/mp4_demuxer.js
Reverts w3c/webcodecs#524
I thought the initial commit broke the sample, but it turns out the error was from a plugin script that I had installed. In my local testing I've verified that the sample works fine with the initial commit applied, so lets revert back to that.
=> Revert "Revert "Fix the problem that getAvccBox cannot get the value when the first track of the video is not AVC""

samples/audio-video-player/audiosink.js
This PR just removes a property from the `AudioSink` in the example code. I believe it's not in use anywhere.
=> Remove unused property from example code

codec_registry.src.html
As the spec uses Markdown, some of the `*` characters were interpreted by Bikeshed as a request to turn the string in italics, whereas we actually want to render the asterisk characters. For instance, `hev1.*, hvc1.*` was rendered as `hev1. <em>, hvc1.<em>`.
This update escapes the asterisk character in codec strings.
=> Codec registry: escape "*" in codec strings

index.src.html
This fixes #515.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/541.html" title="Last updated on Aug 29, 2022, 1:34 PM UTC (24a7d8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/541/3dfd474...24a7d8c.html" title="Last updated on Aug 29, 2022, 1:34 PM UTC (24a7d8c)">Diff</a>
=> Fix visible rect comparison to use strict equality to allow for visible rect of the same size as coded size

index.src.html
This fixes #554
***
<a href="https://pr-preview.s3.amazonaws.com/bdrtc/webcodecs/pull/555.html" title="Last updated on Sep 5, 2022, 9:13 AM UTC (613f44a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/555/663a095...bdrtc:613f44a.html" title="Last updated on Sep 5, 2022, 9:13 AM UTC (613f44a)">Diff</a>
=> fix a typo in 8.2.1

.github/workflows/auto-publish.yml
Add HEVC (H.265) WebCodecs Registration to the auto-publish script so that the specs gets published to the `gh-pages` branch (and to /TR later on when a first draft note will have been published)
This follows from the [outcome of the call for consensus](https://lists.w3.org/Archives/Public/public-media-wg/2022Jul/0008.html) and from #499. I'll request publication of the spec to /TR once this PR has been merged.
=> [Publication job] Add HEVC WebCodecs registration

index.src.html
Fixes #508 per editors consensus.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/562.html" title="Last updated on Sep 16, 2022, 9:13 PM UTC (4f36291)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/562/938df12...4f36291.html" title="Last updated on Sep 16, 2022, 9:13 PM UTC (4f36291)">Diff</a>
=> Remove ImageDecoderInit.premultiplyAlpha

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/568.html" title="Last updated on Oct 3, 2022, 9:12 AM UTC (29f77a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/568/ae7ca0a...youennf:29f77a5.html" title="Last updated on Oct 3, 2022, 9:12 AM UTC (29f77a5)">Diff</a>
=> Remove EnforceRange to framerate definition since EnforceRange is only for integer types

index.src.html
Chromium launched with this support, but apparently the spec text was never updated. Sorry about that!
Fixes: #289
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/567.html" title="Last updated on Sep 28, 2022, 7:34 PM UTC (0913cb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/567/1db4c21...0913cb5.html" title="Last updated on Sep 28, 2022, 7:34 PM UTC (0913cb5)">Diff</a>
=> Add spec text for serializable encoded chunks.

index.src.html, opus_codec_registration.src.html
This fixes #371
***
<a href="https://pr-preview.s3.amazonaws.com/bdrtc/webcodecs/pull/551.html" title="Last updated on Sep 26, 2022, 2:15 AM UTC (67cc867)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/551/1db4c21...bdrtc:67cc867.html" title="Last updated on Sep 26, 2022, 2:15 AM UTC (67cc867)">Diff</a>
=> Add frameDuration attribute to OpusEncoderConfig

index.src.html
Fixes https://github.com/w3c/webcodecs/issues/575
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/576.html" title="Last updated on Oct 10, 2022, 9:53 AM UTC (3752c3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/576/ea1125d...youennf:3752c3b.html" title="Last updated on Oct 10, 2022, 9:53 AM UTC (3752c3b)">Diff</a>
=> Add AllowShared to EncodedVideoChunkInit data

index.src.html
This implements the color spaces portion of #384, but does not add pixel formats or HDR metadata.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/566.html" title="Last updated on Sep 26, 2022, 6:31 PM UTC (b8dd618)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/566/1db4c21...b8dd618.html" title="Last updated on Sep 26, 2022, 6:31 PM UTC (b8dd618)">Diff</a>
=> Add WCG color spaces.

.github/workflows/auto-publish.yml, .gitignore, index.src.html, video_frame_metadata_registry.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/559.html" title="Last updated on Oct 20, 2022, 8:20 AM UTC (8b59018)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/559/938df12...youennf:8b59018.html" title="Last updated on Oct 20, 2022, 8:20 AM UTC (8b59018)">Diff</a>
=> [WebCodecs VideoFrame metadata registry] Introduce VideoFrame metadata

index.src.html
No need to do in prose what Web IDL can achieve.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webcodecs/pull/591.html" title="Last updated on Oct 20, 2022, 7:40 AM UTC (a6d5c71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/591/34b6ed2...tidoust:a6d5c71.html" title="Last updated on Oct 20, 2022, 7:40 AM UTC (a6d5c71)">Diff</a>
=> Add null defaults to VideoColorSpaceInit members

index.src.html
it really is about the timestamp in VideoFrameInit, not the attribute of VideoFrame
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/webcodecs/pull/587.html" title="Last updated on Oct 19, 2022, 3:08 PM UTC (1aef32c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/587/9ad546a...dontcallmedom:1aef32c.html" title="Last updated on Oct 19, 2022, 3:08 PM UTC (1aef32c)">Diff</a>
=> Move note on meaningful timestamp to VideoFrame constructor

index.src.html, video_frame_metadata_registry.src.html
A registry cannot contain normative IDL, so the base definition of the `VideoFrameMetadata` dictionary should remain in WebCodecs.
Also note that while the registry will be published as a "W3C Draft Registry", the document in the repo remains an "Editor's Draft". Updating the status accordingly.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webcodecs/pull/596.html" title="Last updated on Oct 21, 2022, 12:18 PM UTC (faef414)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/596/d7edc37...tidoust:faef414.html" title="Last updated on Oct 21, 2022, 12:18 PM UTC (faef414)">Diff</a>
=> Move VideoFrameMetadata dfn to WebCodecs

index.src.html
This applies to `EncodedVideoChunk`, `EncodedAudioChunk`, `AudioData` and `VideoFrame`, and fixes issue #589.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/590.html" title="Last updated on Oct 20, 2022, 7:09 AM UTC (bc750fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/590/34b6ed2...bc750fd.html" title="Last updated on Oct 20, 2022, 7:09 AM UTC (bc750fd)">Diff</a>
=> When serializing some WebCodecs objects with `forStorage=true`, throw `DataCloneError` instead of `TypeError`

opus_codec_registration.src.html
This PR adds in-band-FEC, DTX and complexity configuration knobs to the Opus encoder.
This should fix #244 and #527
=> Add OpusEncoderConfig parameters

video_frame_metadata_registry.src.html
Following the discussion in #559, this PR covers further changes to adding, changing, and deprecating registry entries.
=> Add requirements to VideoFrame metadata registry definition

aac_codec_registration.src.html, alaw_codec_registration.src.html, av1_codec_registration.src.html, avc_codec_registration.src.html, codec_registry.src.html, flac_codec_registration.src.html, hevc_codec_registration.src.html, index.src.html, mp3_codec_registration.src.html, opus_codec_registration.src.html, pcm_codec_registration.src.html, ulaw_codec_registration.src.html, vorbis_codec_registration.src.html, vp8_codec_registration.src.html, vp9_codec_registration.src.html
Here's a PR to note @chcunningham is now a former editor of the WebCodecs specs.     Chris, if you're watching, please LGTM.
I also took the liberty of removing some duplicate text in the opus codec registration that was causing bikeshed to complain about duplicate definitions.
***
<a href="https://pr-preview.s3.amazonaws.com/mfoltzgoogle/webcodecs/pull/610.html" title="Last updated on Nov 16, 2022, 10:09 PM UTC (2079174)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/610/71b75a6...mfoltzgoogle:2079174.html" title="Last updated on Nov 16, 2022, 10:09 PM UTC (2079174)">Diff</a>
=> Mark Chris as a former editor of WebCodecs specs.

index.src.html
According to the text, which I hope I read correctly:
- The coded width and coded height must be even. So image cannot be 16x9. This update makes it 16x10.
- There should be one Y byte per pixel, so 16x10 Y bytes (example only had 14 bytes per row).
- The U and V components are sub-sampled horizontally and vertically by a factor of 2, and interleaved, so there should 16x10/4 = 40 UV blocks (example only sub-sampled horizontally).
This update also fixes occurrences of "horizontaly".
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webcodecs/pull/630.html" title="Last updated on Jan 24, 2023, 2:37 PM UTC (6728d4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/630/47b8051...tidoust:6728d4e.html" title="Last updated on Jan 24, 2023, 2:37 PM UTC …
=> Fix memory layout of NV12 image example

aac_codec_registration.src.html, alaw_codec_registration.src.html, av1_codec_registration.src.html, avc_codec_registration.src.html, codec_registry.src.html, flac_codec_registration.src.html, hevc_codec_registration.src.html, index.src.html, mp3_codec_registration.src.html, opus_codec_registration.src.html, pcm_codec_registration.src.html, ulaw_codec_registration.src.html, video_frame_metadata_registry.src.html, vorbis_codec_registration.src.html, vp8_codec_registration.src.html, vp9_codec_registration.src.html
Bikeshed now contains cross-reference anchors from Webref, which means it now knows about a number of "new" specifications, including WebCodecs, Media Capture specs, the Infra standard, etc. See announcement at: https://lists.w3.org/Archives/Public/spec-prod/2023JanMar/0004.html
In turn, this means that WebCodecs specs no longer need to list and maintain a local database of cross-references, except in rare cases (such as when a term is not exported by the referenced spec).
This update drops local definitions where ever possible, adjusting references in the prose as needed. A few definitions remain here and there to list external terms that are not exported, along with a couple of linking defaults in the WebCodecs spec.
<del>One temporary hiccup: the markup definitions of …
=> Drop local custom definitions where possible

samples/encode-decode-worker/css/main.css, samples/encode-decode-worker/index.html, samples/encode-decode-worker/js/main.js, samples/encode-decode-worker/js/stream_worker.js
This is a sample demonstrating WebCodecs Encode and Decode in a worker.  A live demo is here: https://webrtc.internaut.com/wc/wcWorker2/
Partial fix for https://github.com/w3c/webcodecs/issues/78
=> Add WebCodecs in Worker sample

index.src.html
Seems to be an oversight from when ondequeue events were added. Allows the idlharness.js test to start passing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/637.html" title="Last updated on Feb 3, 2023, 8:32 PM UTC (734bd7a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/637/c846f98...734bd7a.html" title="Last updated on Feb 3, 2023, 8:32 PM UTC (734bd7a)">Diff</a>
=> Annotate encoder/decoders with EventTarget on ondequeue events.

samples/lib/audio_renderer.js, samples/lib/video_renderer.js
I've noticed that the usage of `isConfigSupported()` in the example is probably not as intended. So far the assertion only checks if `isConfigSupported()` returns a truthy value which is always the case.
I've changed the code to match the usage here: 
https://github.com/w3c/webcodecs/blob/34e21cb731360339b249ceeb6234129a011b92c9/samples/capture-to-file/encode-worker.js#L38-L39
Please let me know if there is anything I should change.
=> Fix usage of {Audio/Video}Decoder.isConfigSupported() in example

index.src.html, vp9_codec_registration.src.html
A codec specific quantizer is set for each video frame for constant quality or fine tuned external rate control.
Addressing Issue [270](https://github.com/w3c/webcodecs/issues/270)
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/633.html" title="Last updated on Feb 28, 2023, 7:38 AM UTC (40954c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/633/704c167...Djuffin:40954c3.html" title="Last updated on Feb 28, 2023, 7:38 AM UTC (40954c3)">Diff</a>
=> Introducing a codec specific 'quantizer' mode for VideoEncoder

index.src.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 17, 2023, 10:24 AM UTC)_.
<details>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fyouennf%2Fwebcodecs%2F537e99dd7d761321ce691ce8edfa780c9d40f00f%2Findex.src.html&md-warning=not%20ready)
```
Error running preprocessor, returned code: 2.
FATAL ERROR: Quoted attribute was never closed
✘  Did not generate, due to fatal errors
```
_If you don't have enough information …
=> Use is not origin-clean concept in VideoFrame constructor

av1_codec_registration.src.html
This value is used by VideoEncoder.encode() if VideoEncoder is configured with "quantizer" bitrate mode.
Follow up for: https://github.com/w3c/webcodecs/issues/270
=> Per frame quantizer option for Av1.

avc_codec_registration.src.html
This value is used by VideoEncoder.encode() if VideoEncoder is configured with "quantizer" bitrate mode. 
Followup for: #270
=> Add per-frame QP support to AVC

av1_codec_registration.src.html
Fixes https://github.com/w3c/webcodecs/issues/646
Rebase of https://github.com/w3c/webcodecs/pull/652
=> Enable configuration of AV1 screen content coding tools

index.src.html
This fixes #485.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/671.html" title="Last updated on May 10, 2023, 5:13 PM UTC (052d98c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/671/3ec4530...052d98c.html" title="Last updated on May 10, 2023, 5:13 PM UTC (052d98c)">Diff</a>
=> Clone configuration should perform a deep copy

samples/encode-decode-worker/js/main.js
This fixes the error popup when doing video source switch.
=> Define videoSource before videoSelect.onchange to avoid ReferenceError.

index.src.html
This should allow to avoid extra copies while constructing VideoFrame from pixel data
Addressing: https://github.com/w3c/webcodecs/issues/104
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/676.html" title="Last updated on Jun 2, 2023, 3:13 AM UTC (4897397)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/676/3a96dbd...Djuffin:4897397.html" title="Last updated on Jun 2, 2023, 3:13 AM UTC (4897397)">Diff</a>
=> Add VideoFrameBufferInit.transfer

index.src.html
See https://github.com/w3c/webcodecs/pull/685#issuecomment-1602409644. This removes the last remaining SHOULD in the Security Considerations section.
Fixes https://github.com/w3c/webcodecs/issues/689
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/691.html" title="Last updated on Jun 22, 2023, 9:46 PM UTC (f648a57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/691/fb21d67...f648a57.html" title="Last updated on Jun 22, 2023, 9:46 PM UTC (f648a57)">Diff</a>
=> Replace RFC2119 wording in Security Considerations

index.src.html
Fixes https://github.com/w3c/webcodecs/issues/689
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webcodecs/pull/690.html" title="Last updated on Jun 22, 2023, 8:55 PM UTC (0f12a6c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/690/fb21d67...aboba:0f12a6c.html" title="Last updated on Jun 22, 2023, 8:55 PM UTC (0f12a6c)">Diff</a>
=> Fix normative language issues

codec_registry.src.html
This is intended to resolve #426.
- Added a requirement for a public specification that is stable
- Added that the WG may consult external expertise as part of its review (but not go so far as producing a written review with a recommendation, as #426 suggested)
- Fixes the numbering in the source document
@aboba for review
=> Add to codec registry requirements

index.src.html
This should allow to avoid extra copies while constructing ImageDecoderInit from encoded image ArrayBuffer
Addressing: https://github.com/w3c/webcodecs/issues/104
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/696.html" title="Last updated on Jun 27, 2023, 9:42 PM UTC (4b6dac0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/696/a7ea132...Djuffin:4b6dac0.html" title="Last updated on Jun 27, 2023, 9:42 PM UTC (4b6dac0)">Diff</a>
=> Add ImageDecoderInit.transfer

samples/encode-decode-worker/js/stream_worker.js
`VideoEncoder.isConfigSupported()` sometimes will return result after `transform()` callback's execution, which will resulting `encoder.encode()` fails to encode a VideoFrame.
We can instead change `start()` to an async function, then `transform()` will always be called after `encoder.configure()`.
=> Fix bug for `WebCodecs in Worker` sample page

index.src.html
User agents shouldn't throw a `TypeError` when an unrecognized codec string is 
encountered since this is harmful for interop (e.g., one UA may only recognize 
some versions of a codec string as valid according to its own codec specification).
This change removes the language around checking valid codec strings when 
determining if a config is valid. It instead adds that language explicitly to 
the "Check Configuration Support" algorithm so `false` or `NotSupportedError` 
can be triggered in `isConfigSupported` and`configure` respectively.
Fixes #686
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/707.html" title="Last updated on Jul 21, 2023, 7:08 PM UTC (1e0fbe3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/707/c462aa4...1e0fbe3.html" …
=> Remove ambiguity around valid codec strings during support checks.

index.src.html
This change allows non-sample-aligned coded sizes and copy rects, and the sample formats are updated to define their meaning (subsampled planes round up in size).
Fixes #638.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/666.html" title="Last updated on May 24, 2023, 6:43 PM UTC (efda26d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/666/2da7339...efda26d.html" title="Last updated on May 24, 2023, 6:43 PM UTC (efda26d)">Diff</a>
=> Support odd coded sizes and copy rects

index.src.html
This PR fixes #699.
It sets `AudioEncoderConfig.bitrateMode` to `"variable"` by default. This matches the VideoEncoder's behavior, and the behavior from the [media recorder spec](https://w3c.github.io/mediacapture-record/#dom-mediarecorderoptions-audiobitratemode).
***
<a href="https://pr-preview.s3.amazonaws.com/tguilbert-google/webcodecs/pull/700.html" title="Last updated on Jul 6, 2023, 7:44 PM UTC (7c5143b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/700/249e328...tguilbert-google:7c5143b.html" title="Last updated on Jul 6, 2023, 7:44 PM UTC (7c5143b)">Diff</a>
=> Add AudioEncoderConfig.bitrateMode default

.github/workflows/auto-publish.yml
The requested status was still "Note" whereas the spec transitioned to the Registry track. Updating the status accordingly.
Note that the job succeeded because it failed to detect the error returned by Echidna to complain about the incorrect status. Spec updates were not published though (and the /TR version is still the October 2022 version for now).
=> Fix auto-publication of the WebCodecs Codec Registry

index.src.html
Make close algorithm synchronously call the error callback and ensure the close algorithm is never called from a parallel queue. Update isConfigSupported to stop resolving the promise from a parallel queue.
This should partially fix https://github.com/w3c/webcodecs/issues/719.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/721.html" title="Last updated on Sep 27, 2023, 1:34 PM UTC (cdc456f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/721/261401a...youennf:cdc456f.html" title="Last updated on Sep 27, 2023, 1:34 PM UTC (cdc456f)">Diff</a>
=> Update configure methods to use a parallel queue to run the the configuration check support

samples/encode-decode-worker/index.html, samples/encode-decode-worker/js/main.js, samples/encode-decode-worker/js/stream_worker.js
These changes add encode and decode time graphs to the Webcodecs encode/decode in worker sample. 
A live version of the sample is here:
https://webrtc.internaut.com/wc/wcWorker2/
=> Add encode/decode time graphs to encode-decode sample

samples/encode-decode-worker/js/stream_worker.js
When the encoder spits out a decoder configuration, set optimizeForLatency based on the encoder configuration of latencyPref.
=> Set optimizeForLatency in decoder config

index.src.html
This should allow to avoid extra copies while constructing  EncodedVideoChunk and EncodedAudioChunk from an ArrayBuffer
Addressing last remnants of: https://github.com/w3c/webcodecs/issues/104
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/728.html" title="Last updated on Oct 6, 2023, 8:49 AM UTC (fb9184d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/728/77944c3...Djuffin:fb9184d.html" title="Last updated on Oct 6, 2023, 8:49 AM UTC (fb9184d)">Diff</a>
=> Add EncodedVideoChunkInit.transfer and EncodedAudioChunkInit.transfer

index.src.html
I noticed a few places where we use MUST and SHOULD but without wrapping them in `<em>` tags.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/730.html" title="Last updated on Oct 17, 2023, 10:48 PM UTC (e2378ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/730/306e516...e2378ec.html" title="Last updated on Oct 17, 2023, 10:48 PM UTC (e2378ec)">Diff</a>
=> Add <em> tags for RFC2119 key words

index.src.html
This fixes #511.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/739.html" title="Last updated on Oct 31, 2023, 2:39 PM UTC (51ee334)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/739/3c9e353...51ee334.html" title="Last updated on Oct 31, 2023, 2:39 PM UTC (51ee334)">Diff</a>
=> Fix incorrect computation in Compute Layout and Allocation Size when figuring out the destination rect

index.src.html
Does what it says. Whitespace fixes split in a different patches for clarity.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/737.html" title="Last updated on Oct 31, 2023, 2:13 PM UTC (61860a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/737/3c9e353...61860a3.html" title="Last updated on Oct 31, 2023, 2:13 PM UTC (61860a3)">Diff</a>
=> Assign [[format]] in VideoFrame ctor

index.src.html
This fixes #510.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/738.html" title="Last updated on Oct 31, 2023, 2:32 PM UTC (441d96c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/738/3c9e353...441d96c.html" title="Last updated on Oct 31, 2023, 2:32 PM UTC (441d96c)">Diff</a>
=> Resolve VideoFrame.copyTo with the list of layout

index.src.html
`sampleWidthBytes` is now unused.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/741.html" title="Last updated on Nov 2, 2023, 10:13 AM UTC (bb03534)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/741/58270fa...bb03534.html" title="Last updated on Nov 2, 2023, 10:13 AM UTC (bb03534)">Diff</a>
=> Fix unused variable

index.src.html
Found while implementing, simple mistake but I think the intent is clear.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/749.html" title="Last updated on Nov 23, 2023, 10:49 AM UTC (f447169)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/749/a04d18b...f447169.html" title="Last updated on Nov 23, 2023, 10:49 AM UTC (f447169)">Diff</a>
=> Use the correct size in "Output EncodedVideoChunks" algorithm when outputing decoder config

opus_codec_registration.src.html
This PR fixes a minor typo in the Opus codec registration.
=> Fix typo in Opus codec registration

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/763.html" title="Last updated on Jan 29, 2024, 9:11 AM UTC (4b530f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/763/21e4a15...youennf:4b530f5.html" title="Last updated on Jan 29, 2024, 9:11 AM UTC (4b530f5)">Diff</a>
=> Export Close VideoFrame as it is used in mediacapture-transform spec

index.src.html
This is what Chromium (at least) does. This means isConfigSupported and configure will now throw if description has been detached.
This also fixes a bug in the ImageDecoder version of this.
This fixes #762.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/764.html" title="Last updated on Jan 31, 2024, 10:26 AM UTC (250f7d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/764/9e0f22e...250f7d8.html" title="Last updated on Jan 31, 2024, 10:26 AM UTC (250f7d8)">Diff</a>
=> {Audio,Video}DecoderConfig with detached description are invalid

index.src.html
Fixes #735, addresses comments from #758.
This PR removes the note from `VideoEncoderConfig.contentHint` and forces User Agent to respect other explicitly set encoder options.
It also adds an equivalent `AudioEncoderConfig.contentHint` section.
***
<a href="https://pr-preview.s3.amazonaws.com/tguilbert-google/webcodecs/pull/759.html" title="Last updated on Feb 5, 2024, 10:31 PM UTC (0795078)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/759/21e4a15...tguilbert-google:0795078.html" title="Last updated on Feb 5, 2024, 10:31 PM UTC (0795078)">Diff</a>
=> Clarify VideoEncoderConfig.contentHint

index.src.html
In the steps for the VideoFrame constructor using a buffer, it specifies to use `options.layout`. But, there is no `options`; it's `init.layout`. This is presumably just a typo from copying from copyTo.
***
<a href="https://pr-preview.s3.amazonaws.com/Yahweasel/webcodecs/pull/769.html" title="Last updated on Feb 27, 2024, 10:06 PM UTC (3728cff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/769/e979025...Yahweasel:3728cff.html" title="Last updated on Feb 27, 2024, 10:06 PM UTC (3728cff)">Diff</a>
=> In the VideoFrame buffer constructor, init.layout, not options.layout

index.src.html
Addressing: https://github.com/w3c/webcodecs/issues/768
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/771.html" title="Last updated on Feb 28, 2024, 9:37 PM UTC (73f325b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/771/724ad87...Djuffin:73f325b.html" title="Last updated on Feb 28, 2024, 9:37 PM UTC (73f325b)">Diff</a>
=> Avoid non-normative uses of "may"

index.src.html
This change adds the planar YUV formats described in issue #384, most of which are 10 or 12-bit. (P010/P012/P016/RGBAF16 are not included.)
***
<a href="https://pr-preview.s3.amazonaws.com/sandersdan/webcodecs/pull/766.html" title="Last updated on Feb 20, 2024, 8:53 PM UTC (b7c9e46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/766/e979025...sandersdan:b7c9e46.html" title="Last updated on Feb 20, 2024, 8:53 PM UTC (b7c9e46)">Diff</a>
=> Add HBD YUV Planar pixel formats

index.src.html
Addressing https://github.com/w3c/webcodecs/issues/774
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/776.html" title="Last updated on Mar 5, 2024, 3:25 AM UTC (970b34b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/776/724ad87...Djuffin:970b34b.html" title="Last updated on Mar 5, 2024, 3:25 AM UTC (970b34b)">Diff</a>
=> Fix a typo in Compute Layout and Allocation Size algorithm

opus_codec_registration.src.html
Follow up work for #759.
`AudioEncoderConfig.contenHint` was not added, since only the Opus codec would benefit from it. Instead, we favored adding the individual codec configuration parameters directly to the Opus registry.
This PR adds `OpusEncoderConfig.signal` and `OpusEncoderConfig.application`.
=> Add OpusEncoderConfig.[signal/application]

index.src.html
They are not required for decoding -- this depends on the codec.
This fixes #714.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/780.html" title="Last updated on Mar 15, 2024, 10:04 AM UTC (0446a14)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/780/c97f298...0446a14.html" title="Last updated on Mar 15, 2024, 10:04 AM UTC (0446a14)">Diff</a>
=> sampleRate and numberOfChannels are required and have to be non-zero in a valid AudioEncoderConfig

index.src.html
Addressing https://github.com/w3c/webcodecs/issues/773
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/775.html" title="Last updated on Mar 5, 2024, 3:24 AM UTC (bb757da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/775/724ad87...Djuffin:bb757da.html" title="Last updated on Mar 5, 2024, 3:24 AM UTC (bb757da)">Diff</a>
=> Add missing metadata to VideoFrameBufferInit

index.src.html
This change should address the [issue](https://github.com/w3c/webcodecs/issues/92) of pixel format conversion in `VideoFrame.copyTo()`.
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/754.html" title="Last updated on Apr 16, 2024, 8:43 AM UTC (0df4aee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/754/871ccb3...Djuffin:0df4aee.html" title="Last updated on Apr 16, 2024, 8:43 AM UTC (0df4aee)">Diff</a>
=> Spec optional conversion to RGB in VideoFrame.copyTo()

av1_codec_registration.src.html
`av1.forceScreenContentTools` was made practically obsolete by [contentHint](https://www.w3.org/TR/webcodecs/#dom-videoencoderconfig-contenthint), which does the same but in a codec-agnostic way.
It hasn't been implemented by any UA, and it's safe to remove from the spec.
This reverts commits:
b35c6a36cb45ceaea87344702aa1c53430daaa56
29f1a8a165c2a16dc9a0b7180bd23c5ac2f07215
Related issue: https://github.com/w3c/webcodecs/issues/646
=> Revert "Add screen content coding tools as an encoder configuration"

index.src.html
Addressing: https://github.com/w3c/webcodecs/issues/788
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/789.html" title="Last updated on May 17, 2024, 10:42 PM UTC (e24df65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/789/dcbf0ce...e24df65.html" title="Last updated on May 17, 2024, 10:42 PM UTC (e24df65)">Diff</a>
=> Change type of EncodedVideoChunkInit.data to AllowSharedBufferSource

index.src.html
Updates the text to clarify when these promises should be  rejected based on what layout tests and sole implementation  currently does.
Fixes #793
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/795.html" title="Last updated on Jun 5, 2024, 8:31 PM UTC (2fc8ad1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/795/485f58e...2fc8ad1.html" title="Last updated on Jun 5, 2024, 8:31 PM UTC (2fc8ad1)">Diff</a>
=> Clarify when ImageDecoder ready, completed promises are rejected.

index.src.html
This PR replaces `EncodedVideoChunk` with `EncodedAudioChunk` in https://w3c.github.io/webcodecs/#encoded-audio-chunk-metadata.
***
<a href="https://pr-preview.s3.amazonaws.com/chrisguttandin/webcodecs/pull/818.html" title="Last updated on Jul 10, 2024, 7:32 PM UTC (bb04436)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/818/39c85f5...chrisguttandin:bb04436.html" title="Last updated on Jul 10, 2024, 7:32 PM UTC (bb04436)">Diff</a>
=> Fix audio/video mix-up

mp3_codec_registration.src.html
This PR removes a duplicate codec string from the MP3 Registration. For some reason `mp4a.69` is mentioned twice.
https://w3c.github.io/webcodecs/mp3_codec_registration.html#fully-qualified-codec-strings
I'm not entirely sure though if that duplication was intentional because it was already part of the issue that motivated this change: https://github.com/w3c/webcodecs/issues/333.
=> Remove duplicate codec string

index.src.html
This is what Chromium implements, but we forgot to update the spec when other data fields were changed to allow shared buffers.
Fixes #799
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/802.html" title="Last updated on Jun 10, 2024, 5:00 PM UTC (90ab77c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/802/9eaaad4...90ab77c.html" title="Last updated on Jun 10, 2024, 5:00 PM UTC (90ab77c)">Diff</a>
=> Mark ImageDecoderInit.data as AllowSharedBufferSource.

index.src.html
Fix for https://github.com/w3c/webcodecs/issues/809
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/812.html" title="Last updated on Jul 3, 2024, 1:12 PM UTC (c3de570)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/812/7073bbf...c3de570.html" title="Last updated on Jul 3, 2024, 1:12 PM UTC (c3de570)">Diff</a>
=> VideoFrame.timestamp and EncodedVideoChunk.timestamp

samples/encode-decode-worker/js/stream_worker.js
Update encode/decode in worker sample to support `optimizeForLatency` and encoder state.
=> Encode/decode in worker sample: Update for low latency, encoder state

samples/encode-decode-worker/js/main.js
Update default settings and codec strings for the encode/decode in worker demo.
=> Encode/decode in worker sample: Update default settings and codec strings

index.src.html
When describing VideoFrame conversion to RGB PredefinedColorSpace can't be used as a VideoFrame.colorSpace and it needs to be converted to the appropriate type ( VideoColorSpace )
Fixes: https://github.com/w3c/webcodecs/issues/831
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/835.html" title="Last updated on Sep 11, 2024, 10:53 PM UTC (737c7a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/835/6fd01eb...Djuffin:737c7a2.html" title="Last updated on Sep 11, 2024, 10:53 PM UTC (737c7a2)">Diff</a>
=> Convert PredefinedColorSpace to VideoColorSpace

index.src.html
This PR addresses https://github.com/w3c/webcodecs/issues/669
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/836.html" title="Last updated on Oct 2, 2024, 2:27 AM UTC (b5e1d38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/836/6fd01eb...Djuffin:b5e1d38.html" title="Last updated on Oct 2, 2024, 2:27 AM UTC (b5e1d38)">Diff</a>
=> Allow newly created codecs to be reclaimed if the system is out of resources

index.src.html
Adds `rotation` and `flip` to `VideoFrame` and `VideoFrame` constructor `init` dictionaries, as described in https://github.com/w3c/webcodecs/issues/351#issuecomment-2359389479.
Does not include any changes to `VideoDecoder`, `VideoEncoder`, or `ImageDecoder`.
I do not allow buffer-initialized `VideoFrame`s to end up with orientations other than requested, which differs from the proposal slightly, but is probably more obvious for developers.
I assume that `Canvas` and `ImageBitmap` sources do not have natural orientations. I do not know if this is reasonable.
There is handwaving around the natural orientation of `ImageElement` sources, as I did not find any spec text that describes how EXIF orientation is actually handled.
***
<a …
=> Add orientation to VideoFrame

explainer.md
The article moved and its old link returns a 404, but here's the new link
=> update link to the chrome webcodecs article

video_frame_metadata_registry.src.html
These fields are useful for WebRTC-based applications.
See issue #601
=> Add captureTime, receiveTime and rtpTimestamp to VideoFrameMetadata

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyavenard/webcodecs/pull/863.html" title="Last updated on Dec 12, 2024, 12:13 AM UTC (a73e6d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/863/41636a6...jyavenard:a73e6d5.html" title="Last updated on Dec 12, 2024, 12:13 AM UTC (a73e6d5)">Diff</a>
=> Fix various step counts in original source.

samples/lib/audio_renderer.js
Per spec https://w3c.github.io/webcodecs/#dom-audiodatacopytooptions-format if the format is not specified, we are to use the same format as the source. Which could be interleaved as the format for decoding isn't specified.
Calling copyTo with a planeIndex of 0 with an interleaved buffer will attempt to copy all planes.
So we just set the destination format to be f32-planar.
This allows playback to start on browsers that aren't Blink based (Firefox, Safari)
=> Specify format of buffer we're copying into

samples/lib/web_audio_controller.js
Not all User Agents implement AudioContext.outputLatency (such as Safari). On those, totalOutputLatency would always be NaN, resulting in no video frames ever displayed.
=> Handle case where AudioContext.outputLatency isn't implemented.

index.src.html
As proposed on the issue and discussed in WG, this does the following:
- Adds rotation/flip fields to VideoDecoderConfig.
- Updates the "Create a VideoFrame" algorithm used by the video and image decoders to accept these fields.
- Updates the video and image decoding algorithms to provide these fields during decoding.
Bug: https://github.com/w3c/webcodecs/issues/351
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/874.html" title="Last updated on Jan 29, 2025, 12:28 AM UTC (0184fb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/874/b9a8e34...0184fb5.html" title="Last updated on Jan 29, 2025, 12:28 AM UTC (0184fb5)">Diff</a>
=> Add orientation metadata to VideoDecoderConfig, update algorithms

.github/workflows/deploy-images.yml, .github/workflows/deploy-samples.yml
[GitHub will no longer support the Ubuntu 20.04 runner image starting from April 1, 2025](https://github.com/actions/runner-images/issues/11101). That PR updates the actions to use ubuntu-latest instead
=> GitHub actions: replace ubuntu-20.04 with ubuntu-latest

index.src.html
This implements the algorithm as discussed in the Media WG:
* Orientation is locked-in upon the first call to encode().
* Mismatched orientation will trigger a non-fatal error by throwing an exception during encode().
* The orientation of the first frame is emitted on the VideoDecoderConfig attached to EncodedVideoChunkMetadata.
Fixes: https://github.com/w3c/webcodecs/issues/351
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/884.html" title="Last updated on Mar 14, 2025, 7:02 PM UTC (e3bd401)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/884/011346f...e3bd401.html" title="Last updated on Mar 14, 2025, 7:02 PM UTC (e3bd401)">Diff</a>
=> Implement orientation support for VideoEncoder.

video_frame_metadata_registry.src.html
This adds the field that is being proposed in https://github.com/w3c/webcodecs/issues/839
=> Add backgroundBlur to VideoFrameMetadata registry

index.src.html
Mirroring https://github.com/w3c/webcodecs/pull/582.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/888.html" title="Last updated on Apr 17, 2025, 12:46 PM UTC (c5257e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/888/dc3cf30...c5257e2.html" title="Last updated on Apr 17, 2025, 12:46 PM UTC (c5257e2)">Diff</a>
=> Make AudioDecoderConfig.description AllowShared

avc_codec_registration.src.html, hevc_codec_registration.src.html
This resolves: https://github.com/w3c/webcodecs/issues/890
=> Update reference to iso14496-15

video_frame_metadata_registry.src.html
Background segmentation mask is useful for Media Capture as discussed in https://github.com/w3c/mediacapture-extensions/pull/142.
=> Add backgroundSegmentationMask to VideoFrameMetadata registry
