w3c/webcodecs

explainer.md
PTAL @pthatcherg @padenot
Should we allow instantiation inside service workers? I could see a use case for transcoding files as they download.
=> Add detailed design discussion for execution environments

explainer.md
The recency should be obvious based on the commit log.
=> Remove last updated from the explainer

explainer.md
- Simplify some code (e.g., MediaStream constructor)
- Bring into compliance with recent configuration design change
- Some style changes
=> Update explainer examples

Makefile, index.bs
Skeleton for bikeshed spec and Makefile with some early idl.
=> Setup bikeshed

explainer.md
Major changes to API shape. See rationale in
"Alternative designs considered".
Removes streamy aspects from interface.
Updates all examples.
Updates discussion of worker transfer.
Updates discussion of codec configuration.
Adds discussion of streams to "Alternative designs considered"
Adds "Future considerations" with mix of old/new ideas.
Addresses parts of #35. Will send a second CL with full IDL to completely address that.
=> Update explainer (decouple from streams)

Makefile, index.src.html
This ports the [google doc](https://docs.google.com/document/d/11n6xLkZThJkDc7SBFzUVAynl5kZsxZJtjy_BjbxE8a0/edit?ts=5f153e9e#) into bikeshed. A number of TODO's and open issues mentioned with "NOTE: This needs work". GH issues to be filed shortly.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/73.html" title="Last updated on Aug 27, 2020, 8:04 AM UTC (9c8efff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/73/538ddd8...9c8efff.html" title="Last updated on Aug 27, 2020, 8:04 AM UTC (9c8efff)">Diff</a>
=> Spec first draft

Makefile, index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/74.html" title="Last updated on Aug 28, 2020, 5:08 PM UTC (2b83831)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/74/b410ade...2b83831.html" title="Last updated on Aug 28, 2020, 5:08 PM UTC (2b83831)">Diff</a>
=> Fix all warnings. Little style cleanups.

explainer.md
s/audioEcoder/audioEncoder/
s/audioEnocer/audioEncoder/
=> explainer: fix typos

index.src.html, security-privacy-questionnaire.md
Add sections for security and privacy considerations
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/134.html" title="Last updated on Feb 6, 2021, 5:06 AM UTC (a92dc02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/134/4877869...a92dc02.html" title="Last updated on Feb 6, 2021, 5:06 AM UTC (a92dc02)">Diff</a>
=> Add sections for security and privacy considerations

index.src.html
Add Bernard Aboba of Microsoft as editor
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/pull/146.html" title="Last updated on Feb 25, 2021, 5:14 AM UTC (d2eb8fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/web-codecs/146/ad7469f...d2eb8fa.html" title="Last updated on Feb 25, 2021, 5:14 AM UTC (d2eb8fa)">Diff</a>
=> Add Bernard Aboba of Microsoft as editor

index.src.html
Fixes #164
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/173.html" title="Last updated on Apr 9, 2021, 7:14 AM UTC (e2750f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/173/eefd4c2...e2750f2.html" title="Last updated on Apr 9, 2021, 7:14 AM UTC (e2750f2)">Diff</a>
=> Minor IDL fixes.

codec_registry.src.html
=> Clarify registry review process.

samples/index.html, samples/samples.css
This sets up the basic structure for adding demo samples. It is
heavily inspired by https://webaudioapi.com/samples/
It will be hosted at https://w3c.github.io/webcodecs/samples/
=> Add beginnings of samples directory.

samples/capture-to-file/capture-to-file.html, samples/capture-to-file/webm-writer2.js, samples/index.html
Shows capture from camera, compress and store to a webm file.
=> Add capture-to-file sample

index.src.html
Fixes #160
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/255.html" title="Last updated on May 25, 2021, 1:25 PM UTC (23ca0b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/255/6de978f...23ca0b1.html" title="Last updated on May 25, 2021, 1:25 PM UTC (23ca0b1)">Diff</a>
=> Add [EnforceRange] to all input numbers

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/260.html" title="Last updated on May 27, 2021, 3:02 PM UTC (ba57ce2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/260/e36bf7a...ba57ce2.html" title="Last updated on May 27, 2021, 3:02 PM UTC (ba57ce2)">Diff</a>
=> Replace the term "frame" by the term "object" because audio data are not frames anymore.

index.src.html
Fixes #265.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/277.html" title="Last updated on Jun 11, 2021, 9:25 PM UTC (37c7bee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/277/b3e3cc3...37c7bee.html" title="Last updated on Jun 11, 2021, 9:25 PM UTC (37c7bee)">Diff</a>
=> Add VideoEncoderConfig.bitrateMode for CBR/VBR

samples/capture-to-file/capture-to-file.html, samples/image-decoder/animated-gif-renderer.html, samples/mp4-decode/index.html, samples/webcam-in-worker/index.html
The current OT token is only valid until July 13th. Update it with one that is valid until Aug 20th.
=> Update OT token

index.src.html
Per plan described in #269. Will add framerate in a follow up.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/292.html" title="Last updated on Jul 14, 2021, 5:25 AM UTC (c405b93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/292/09f2655...c405b93.html" title="Last updated on Jul 14, 2021, 5:25 AM UTC (c405b93)">Diff</a>
=> Add latencyMode to VideoEncoderConfig

index.src.html
Fixes #278.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/299.html" title="Last updated on Jul 14, 2021, 5:34 AM UTC (d84edd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/299/512cd4c...d84edd2.html" title="Last updated on Jul 14, 2021, 5:34 AM UTC (d84edd2)">Diff</a>
=> Replace VideoFrameRect with DOMRect

index.src.html
Fixes #206
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/311.html" title="Last updated on Jul 28, 2021, 4:06 PM UTC (bed76bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/311/88e74a4...bed76bb.html" title="Last updated on Jul 28, 2021, 4:06 PM UTC (bed76bb)">Diff</a>
=> Add optimizeForLatency to the spec.

.github/workflows/auto-publish.yml, .gitignore, Makefile, codec_registry.src.html, mp3_codec_registration.src.html
This is using the latest revision of the text (from [1998](https://www.iso.org/standard/26797.html)), so it's in 2.4.2.2, but generally the same as in MSE ("an mp3 frame").
Again this has the Makefile changes so that it builds, please ignore.
=> Add mp3 to the registry

.github/workflows/auto-publish.yml, .github/workflows/deploy-images.yml, index.src.html
Images under the "images" folder were not published to GitHub Pages, resulting in broken links in the spec. This partly explains failure to publish to /TR (see #298).
In addition, images that are referenced by the WebCodecs spec need to be published to Github Pages before publication to /TR occurs, since publication to /TR makes a copy of the image. This update makes the job that takes care of publishing specs to /TR depend on the job that publishes the images.
The job that publishes the images is similar to the one used to deploy samples.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 9, 2021, 3:52 PM UTC)_.
<details>
PR Preview relies on a number of web services to run. There seems to be an issue with the …
=> Publish workflow: deploy images first

avc_codec_registration.src.html, mp3_codec_registration.src.html
=> Accept multiple codec strings for mp3 and h264

opus_codec_registration.src.html
=> Be explicit about Opus bitstream formats

index.src.html
Fixes #350
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/353.html" title="Last updated on Sep 8, 2021, 12:10 AM UTC (58f4b61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/353/9dc3359...58f4b61.html" title="Last updated on Sep 8, 2021, 12:10 AM UTC (58f4b61)">Diff</a>
=> Mark codec interfaces SecureContext

.github/workflows/auto-publish.yml, .gitignore
Updates publish workflow and gitignore to include new pcm, alaw, and ulaw registrations.
=> Update publish & ignore file w/ new registrations

index.src.html
=> Fix the type of the Promise returned by VideoEncoder.isTypeSupported.

av1_codec_registration.src.html
=> Clarify wording in AV1 codec registry.

index.src.html
Fixes #284
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/440.html" title="Last updated on Feb 9, 2022, 5:35 AM UTC (658b6ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/440/14cf28f...658b6ec.html" title="Last updated on Feb 9, 2022, 5:35 AM UTC (658b6ec)">Diff</a>
=> Make *QueueSize attributes unsigned

samples/video-decode-display/demuxer_mp4.js
Support decoding of hevc. sample hevc clip is not submitted unless it is encouraged to upload one without any IP issue.
=> Support decoding of hevc.

samples/ffmpeg-wasm-demuxer/wasm_demuxer_demo.html
(Apologies if I submitted this incorrectly, this is my first contribution to a w3 repo)
Just two typos I noticed trying out this demo
=> ffmpeg-wasm-demuxer sample: fix 2 typos

index.src.html
A huge thank you to all the folks who contributed!
I've tried to remember everyone who's contributed over the years, but I'm sure I've forgotten someone. Please LMK if anyone is missing.  
FYI
Alex Russell - @slightlyoff
Chris Needham - @chrisn 
Dale Curtis - @dalecurtis 
Dan Sanders - @sandersdan 
Eugene Zemtsov - @djuffin
Francois Daoust - @tidoust
Guido Urdaneta - @guidou
Harald Alvestrand - @alvestrand
Jan-Ivar Bruaroey - @jan-ivar
Jer Noble - @jernoble 
Mark Foltz - @mfoltzgoogle
Peter Thatcher - @pthatcher
Steve Anton - @steveanton
Matt Wolenetz - @wolenetz
Rijubrata Bhaumik - @riju
Thomas Guilbert - @tguilbert-google
Tuukka Toivonen - @ttoivone
Youenn Fablet - @youennf
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/547.html" title="Last updated on Sep 1, 2022, …
=> Add Acknowledgements - long overdue!

codec_registry.src.html
This attempts to formalize the policy for changes proposed in https://github.com/w3c/webcodecs/issues/571#issuecomment-1265716042
=> Add policy for changes to existing registry entries

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/582.html" title="Last updated on Oct 14, 2022, 9:18 AM UTC (2612b4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/582/55ca05e...youennf:2612b4f.html" title="Last updated on Oct 14, 2022, 9:18 AM UTC (2612b4f)">Diff</a>
=> Make VideoDecoderConfig.description AllowShared

README.md
This PR updates the readme to link to the new VideoFrame Metadata Registry.
=> Add VideoFrame Metadata Registry to the Readme

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webcodecs/pull/632.html" title="Last updated on Jan 31, 2023, 9:45 AM UTC (20b7172)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/632/dfc5031...tidoust:20b7172.html" title="Last updated on Jan 31, 2023, 9:45 AM UTC (20b7172)">Diff</a>
=> Editorial: fix typos, add missing links

index.src.html
fix several typos
***
<a href="https://pr-preview.s3.amazonaws.com/bdrtc/webcodecs/pull/634.html" title="Last updated on Feb 2, 2023, 6:37 AM UTC (b75eb06)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/634/dfc5031...bdrtc:b75eb06.html" title="Last updated on Feb 2, 2023, 6:37 AM UTC (b75eb06)">Diff</a>
=> fix several typos

samples/index.html
Add a link to the WebCodecs in Worker sample, once merged.
Related: https://github.com/w3c/webcodecs/pull/583
=> Add WebCodecs in Worker link on samples page

samples/capture-to-file/webm-writer2.js
See: https://github.com/w3c/webcodecs/issues/332#issuecomment-1077442192
=> Add nixxquality's fixes

samples/index.html
Fix the link to the "WebCodecs in Worker" sample
=> Fix a link URL

index.src.html, opus_codec_registration.src.html
fixes #649
***
<a href="https://pr-preview.s3.amazonaws.com/bdrtc/webcodecs/pull/657.html" title="Last updated on Apr 18, 2023, 9:18 AM UTC (e54743a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/657/2b856eb...bdrtc:e54743a.html" title="Last updated on Apr 18, 2023, 9:18 AM UTC (e54743a)">Diff</a>
=> support specify audio encode bitrateMode interface

index.src.html
See https://github.com/whatwg/webidl/pull/1311 for context.
***
<a href="https://pr-preview.s3.amazonaws.com/annevk/webcodecs/pull/683.html" title="Last updated on Jun 16, 2023, 10:11 AM UTC (18d4456)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/683/a7ea132...annevk:18d4456.html" title="Last updated on Jun 16, 2023, 10:11 AM UTC (18d4456)">Diff</a>
=> Editorial: account for SharedArrayBuffer change in Web IDL

hevc_codec_registration.src.html
=> Fix HEVC registration text

index.src.html
Adding myself to the WebCodecs editors list.
***
<a href="https://pr-preview.s3.amazonaws.com/Djuffin/webcodecs/pull/703.html" title="Last updated on Jul 7, 2023, 9:32 PM UTC (e2883f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/703/bc2ce23...Djuffin:e2883f2.html" title="Last updated on Jul 7, 2023, 9:32 PM UTC (e2883f2)">Diff</a>
=> Add Eugene Zemtsov to the list of editors

codec_registry.src.html
Non-public specs must be made available to the WG for review
=> Add to codec registration requirements

samples/encode-decode-worker/js/stream_worker.js
Related: https://github.com/w3c/webcodecs/pull/705
=> Fix potential race condition in the decoder (encode-decode in workers sample)

hevc_codec_registration.src.html
Add per-frame QP support to HEVC, handled similarly to AVC, VP9, AV1
=> Add support for per-frame QP to HEVC

samples/encode-decode-worker/index.html, samples/encode-decode-worker/js/main.js, samples/encode-decode-worker/js/stream_worker.js
Adds a chart of glass-glass latency as well as control over use of decoder hardware acceleration.
=> Add g2g latency chart and decoder hw acceleration control

samples/encode-decode-worker/index.html, samples/encode-decode-worker/js/main.js
similar to what was done here:
https://github.com/aboba/wt-demo/pull/4
Before:
After:
(@aboba I thought this was the initial goal ;-))
=> samples: use plotly for drawing the glass-to-glass chart

index.src.html
Fix copy-past errors
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/733.html" title="Last updated on Oct 27, 2023, 11:19 PM UTC (f14cd48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/733/11307bc...f14cd48.html" title="Last updated on Oct 27, 2023, 11:19 PM UTC (f14cd48)">Diff</a>
=> Fix typos in [Video|Audio]Encoder.configure() description

index.src.html
Specs like mediacapture transform
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webcodecs/pull/765.html" title="Last updated on Feb 8, 2024, 5:32 PM UTC (ff09dbe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/765/26e7922...youennf:ff09dbe.html" title="Last updated on Feb 8, 2024, 5:32 PM UTC (ff09dbe)">Diff</a>
=> Export clone video frame algorithm as it is useful in other specs

video_frame_metadata_registry.src.html
Fixes https://github.com/w3c/webcodecs/issues/607
=> Add segments metadata entry that refers to https://w3c.github.io/mediacapture-extensions/#human-face-segmentation
